service: sqs-service

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  consume:
    handler: handlers/sqs-handler.consume
    name: '${self:service}-consume-function'
    events:
      - sqs:
          arn: { Fn::GetAtt: [ sqsQueue, Arn ] }
          batchSize: 1
    environment:
      REGION: ${self:provider.region}

resources:
  Resources:
    sqsQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: '${self:service}-demo-queue'


